"""Build ``out/07_report.md``.

Every number in the report is read out of a JSON file in ``out/`` -- nothing is
recomputed here, so a number in the prose and the number in the artefact cannot
drift apart.  Fold-level values are printed, not just means.
"""
from __future__ import annotations

import numpy as np

from flaky.cv import BASELINE_METHODS
from flaky.structural import PROPERTIES

VERDICT_WORD = {True: "**PASS**", False: "**FAIL**", None: "**INCONCLUSIVE**"}


def _f(x, nd=4):
    if x is None:
        return "—"
    if isinstance(x, float) and (np.isnan(x) or np.isinf(x)):
        return "—"
    return f"{x:.{nd}f}"


def _folds(v, nd=3):
    return ", ".join(_f(x, nd) for x in v)


def build_report(ctx, prep, base, transfer, struct, valid, pairs, probe, verdict,
                 model_key, pool, layer) -> str:
    L: list[str] = []
    A = L.append

    overall = verdict["overall"]
    swb = verdict["strong_word_baseline"]
    s1, s2, s3 = (verdict["criteria"][k] for k in ("S1", "S2", "S3"))
    entry = probe["models"][model_key][pool]

    # ---------------------------------------------------------------- header
    A("# Phase 1 — does a code language model represent test flakiness structurally "
      "or lexically?")
    A("")
    A(f"*Generated by `scripts/s07_decision.py` from `{ctx.out.name}/*.json`. "
      f"Seed {prep['seed']}. Every number below is traceable to a named JSON file.*")
    A("")
    A("## Verdict")
    A("")
    A(f"**{overall.replace('_', ' ').upper()}**")
    A("")
    A("| criterion | statement | verdict |")
    A("|---|---|---|")
    A(f"| S1 | cue-removed probe beats `STRONG_WORD_BASELINE`, cross-project | "
      f"{VERDICT_WORD[s1.get('passes')]} |")
    A(f"| S2 | renaming transfer drop smaller for the probe than for `bow` | "
      f"{VERDICT_WORD[s2.get('passes')]} |")
    A(f"| S3 | minimal-pair accuracy above 0.5 for the probe | "
      f"{VERDICT_WORD[s3.get('passes')]} |")
    A("")
    A("All three must hold to proceed to Phase 2. The stopping rule was fixed in "
      "`plan/00_OVERVIEW.md` before any result was seen; no threshold, baseline or metric "
      "was changed here.")
    A("")

    # ------------------------------------------------------------------- data
    A("## 1. Data")
    A("")
    import os
    try:
        src_rel = os.path.relpath(prep["input"], ctx.root)
    except ValueError:
        src_rel = prep["input"]
    A(f"`{src_rel}` → `{ctx.data.name}/prepped.csv`. Source: `{ctx.out.name}/01_prep.json`.")
    A("")
    A(f"- rows: {prep['n_rows_raw']} raw → **{prep['n_rows_final']}** after dedup "
      f"({prep['n_dup_exact_removed']} exact duplicates, "
      f"{prep.get('n_dup_post_norm_removed', 0)} more after normalisation, "
      f"{prep.get('n_post_norm_conflict_rows_dropped', 0)} dropped for contradictory labels)")
    A(f"- flaky: **{prep['n_flaky']}** ({prep['class_prior']:.4f} of rows) across "
      f"{prep['n_projects']} projects")
    A(f"- length-matched subset: {prep['matched']['n']} rows "
      f"({prep['matched']['n_flaky']}/{prep['matched']['n_non_flaky']}), median `n_tokens` "
      f"{prep['matched']['median_n_tokens_flaky']:.0f} vs "
      f"{prep['matched']['median_n_tokens_non_flaky']:.0f}")
    A("")
    A("### The formatting artefact")
    A("")
    A(f"In the released CSV the two classes are separable by whitespace alone: four booleans "
      f"give **AUROC {_f(prep['whitespace_auroc_before'], 3)}**. "
      f"{prep['whitespace_rates_before_by_class']['non_flaky']['ws_leading_indent']:.1%} of "
      f"non-flaky tests begin with indentation and "
      f"{prep['whitespace_rates_before_by_class']['non_flaky']['ws_ends_with_newline']:.0%} end "
      f"with a newline; **no** flaky test does either. The classes were evidently extracted by "
      f"different pipelines. After normalisation the same four booleans give AUROC "
      f"**{_f(prep['whitespace_auroc_after'], 3)}**.")
    A("")
    A(f"Length is a second confound: flaky tests are longer, and `n_tokens` alone reaches "
      f"AUROC **{_f(prep['length_auroc_full'], 3)}** on the full set "
      f"(**{_f(prep['length_auroc_matched'], 3)}** on the matched subset).")
    A("")
    if prep.get("post_norm_conflicts"):
        c = prep["post_norm_conflicts"]
        A(f"A third data-quality problem, surfaced by normalisation: **{c['n_codes']} test "
          f"methods appear twice with identical code and contradictory labels** "
          f"({c['n_rows']} rows), once as `test order dependency` under a SHA-prefixed "
          f"synthetic name and once as `non-flaky` under the real class name. Neither label "
          f"can be trusted, so both copies were dropped rather than one being silently "
          f"preferred. Listed in `out/01_prep.json`.")
        A("")

    # -------------------------------------------------------------- baselines
    A("## 2. Baselines and the within- vs cross-project gap")
    A("")
    A("Source: `out/02_baselines.json`. 5 folds, stratified, seed 0. `within` uses "
      "`StratifiedKFold`; `cross` uses `StratifiedGroupKFold` grouped by project. "
      "Vectorisers are fitted inside each fold; `C` is tuned on an inner split.")
    A("")
    A("| method | within AP | cross AP | gap | cross AP on `code_renamed` | Δ |")
    A("|---|---|---|---|---|---|")
    for m in BASELINE_METHODS:
        cell = base["methods"].get(m, {}).get("full", {})
        if "cross" not in cell:
            continue
        d = transfer["methods"].get(m, {}).get("delta", {})
        A(f"| `{m}` | {_f(cell['within']['ap']['mean'])} ± {_f(cell['within']['ap']['std'], 3)} "
          f"| {_f(cell['cross']['ap']['mean'])} ± {_f(cell['cross']['ap']['std'], 3)} "
          f"| {cell['gap']['mean']:+.4f} "
          f"| {_f(cell['cross']['ap_on_renamed']['mean'])} "
          f"| {d.get('mean', float('nan')):+.4f} |")
    A("")
    A(f"Class prior on the full set is {base['class_prior_full']:.4f}, so every method is "
      f"well above chance in absolute terms while still losing most of its within-project "
      f"performance when projects are held out.")
    A("")
    A("**Fold-level cross-project AP** (needed for the paired tests, and printed so the "
      "reader sees the spread rather than a mean):")
    A("")
    A("| method | folds |")
    A("|---|---|")
    for m in BASELINE_METHODS:
        cell = base["methods"].get(m, {}).get("full", {})
        if "cross" in cell:
            A(f"| `{m}` | {_folds(cell['cross']['ap']['folds'])} |")
    A("")
    A(f"`STRONG_WORD_BASELINE` = **{_f(swb['ap_mean'])}** (`{swb['method']}`, cross-project, "
      f"full set), fixed in 02 and not renegotiated. Candidates: "
      + ", ".join(f"`{k}` {_f(v)}" for k, v in swb["candidates"].items()) + ".")
    A("")
    mt = base["methods"].get("bow", {}).get("matched", {})
    if "cross" in mt:
        A(f"On the length-matched subset `bow` scores {_f(mt['cross']['ap']['mean'])} "
          f"cross-project against a prior of {_f(base['class_prior_matched'])}, so the "
          f"cross-project signal is not merely length.")
        A("")

    # --------------------------------------------------------------- renaming
    A("## 3. Cue removal and counterfactual renaming")
    A("")
    A("Source: `out/03_rename.json`, `out/03_transfer.json`, `data/cue_vocab.json`.")
    A("")
    ren = None
    try:
        from flaky.common import load_json
        ren = load_json(ctx.out / "03_rename.json")
    except Exception:
        pass
    if ren:
        A(f"- cue vocabulary: {ren['cue_tag_sizes']['attributed']} attributed, "
          f"{ren['cue_tag_sizes']['attributed_curated']} curated extension, "
          f"{ren['cue_tag_sizes']['api']} API/type names; "
          f"{ren['cue_tag_sizes']['mined_audit_only']} mined identifiers are held as an "
          f"audit artefact only and never used to fit anything.")
        A(f"- renaming touched {ren['rows_with_at_least_one_replacement']} rows "
          f"({ren['rows_with_replacement_rate']:.1%}), mean "
          f"{ren['mean_replacements_per_row']:.2f} replacements per row.")
        A(f"- the rewrite is exactly token-count preserving at the Java lexical level "
          f"({ren['java_token_count_equal_rate']:.4f} of rows) because every substitution "
          f"swaps one identifier token for one identifier token. Subword counts still shift "
          f"(mean {ren['codebert_subword_delta']['mean']:+.2f}); reported rather than hidden.")
        A("")
    A("Transfer drop Δ = AP(`code`) − AP(`code_renamed`), cross-project, model trained on "
      "`code`:")
    A("")
    A("| method | Δ mean | Δ folds |")
    A("|---|---|---|")
    for m in BASELINE_METHODS:
        d = transfer["methods"].get(m, {}).get("delta")
        if d:
            A(f"| `{m}` | {d['mean']:+.4f} | {_folds(d['folds'])} |")
    A("")
    rt = transfer["methods"].get("bow", {}).get("retrained_on_renamed")
    if rt:
        A(f"Sanity check: a `bow` model **retrained** on `code_renamed` scores "
          f"{_f(rt['ap']['mean'])}, within one fold-std of its AP on `code` "
          f"({'yes' if rt['within_one_fold_std'] else '**no**'}). Retraining measures nothing "
          f"about lexical reliance — the model simply relearns the neutral names — and is "
          f"reported only to show the renaming is shape-preserving and not leaking.")
        A("")

    # ------------------------------------------------------------- structural
    A("## 4. Structural properties")
    A("")
    A("Source: `out/04_structural.json`, `out/04_validation.md`. Labels come from a "
      "tree-sitter taint pass, never from the flakiness label.")
    A("")
    A(f"- parse failure rate **{struct['parse_failure_rate']:.4f}** (acceptance < 0.05). "
      f"{struct['parse_repairs']['n_repaired']} rows "
      f"({struct['parse_repairs']['rate']:.1%}) needed a truncation repair: FlakeBench cuts "
      f"a fraction of method bodies off mid-statement, and those rows are almost entirely "
      f"non-flaky, so leaving them unparsed would bias the labels. Without repair the "
      f"failure rate is {struct['parse_repairs']['failure_rate_without_repair']:.4f}.")
    A("")
    A("| property | overall | async wait | concurrency | time | unordered coll. | non-flaky |")
    A("|---|---|---|---|---|---|---|")
    pb = struct["prevalence_by_label"]
    for p in PROPERTIES:
        def g(lab):
            return _f(pb.get(lab, {}).get(p), 4)
        A(f"| `{p}` | {_f(struct['prevalence_overall'][p])} | {g('async wait')} | "
          f"{g('concurrency')} | {g('time')} | {g('unordered collections')} | "
          f"{g('non-flaky')} |")
    A("")
    fc = struct["floor_check"]
    A(f"Floor check (not a finding): `P_ASYNC` prevalence in the async-wait category "
      f"{_f(fc['P_ASYNC_rate_async_wait'], 3)} vs non-flaky "
      f"{_f(fc['P_ASYNC_rate_non_flaky'], 3)} — "
      f"{'passes' if fc['passes'] else '**fails, the analysis is broken**'}.")
    A("")
    diag = struct.get("P_ASYNC_definition_diagnostic")
    if diag:
        A(f"A consequence of the definition worth stating: the plan puts `sleep` in the "
          f"synchronisation kill set, so the canonical async-wait flaky shape "
          f"(*dispatch; sleep; assert*) is excluded from `P_ASYNC` by construction. "
          f"{diag['n_rows_that_would_flip']} rows would flip if it were not; the async-wait "
          f"rate would rise from {_f(fc['P_ASYNC_rate_async_wait'], 3)} to "
          f"{_f(diag['rate_in_async_wait_if_sleep_not_a_barrier'], 3)}. This is a diagnostic, "
          f"not a property, and no stopping-rule number depends on it.")
        A("")
    soc = struct["structural_only_classifier"]
    A(f"**Do the structural properties predict flakiness?** A logistic regression on the "
      f"three booleans alone scores cross-project AP **{_f(soc['ap']['mean'])} ± "
      f"{_f(soc['ap']['std'], 3)}** (folds: {_folds(soc['ap']['folds'])}) against a class "
      f"prior of {_f(soc['class_prior'])}. Barely above the prior: on this dataset, the named "
      f"structural properties carry almost no predictive signal for the flakiness label.")
    A("")
    if valid:
        A("**Validation of the analyser** (`out/04_validation.md`, "
          f"{valid['n_audited']} hand-audited methods, auditor: {valid['auditor']}):")
        A("")
        A("| property | precision | recall | retained |")
        A("|---|---|---|---|")
        for p in PROPERTIES:
            e = valid["properties"][p]
            A(f"| `{p}` | {_f(e['precision'], 3)} "
              f"[{_f(e['precision_wilson_95'][0], 2)}, {_f(e['precision_wilson_95'][1], 2)}] "
              f"| {_f(e['recall'], 3)} | "
              f"{'yes' if e['meets_precision_floor'] else '**no — below the 0.8 floor**'} |")
        A("")
        sem = valid.get("semantic") or {}
        if sem:
            A("Those figures score the analyser against the properties **as written**, with "
              "the plan's fixed vocabularies. A second judgement asked whether each property "
              "holds in the code's *actual* behaviour:")
            A("")
            A("| property | semantic precision | semantic recall |")
            A("|---|---|---|")
            for p in PROPERTIES:
                if p in sem:
                    A(f"| `{p}` | {_f(sem[p]['precision'], 3)} "
                      f"({sem[p]['tp']}/{sem[p]['tp'] + sem[p]['fp']}) "
                      f"| {_f(sem[p]['recall'], 3)} |")
            A("")
            pa = sem.get("P_ASYNC", {}).get("precision")
            A(f"The gap is large for `P_ASYNC` ({_f(pa, 3)} semantic against "
              f"{_f(valid['properties']['P_ASYNC']['precision'], 3)} definitional) and it is a "
              f"property of the plan's vocabulary, not of the implementation: `execute` and "
              f"`start` are listed as async dispatches, but Hystrix's `cmd.execute()` is the "
              f"*synchronous* API and `new SystemCtl(t).start(\"docker\")` merely builds a "
              f"command object. This bounds how much a probe trained on these labels can be "
              f"said to have learned about genuine asynchrony, and it is the single largest "
              f"caveat on section 4's structural results.")
            A("")
    else:
        A("**The hand audit has not been run.** `out/04_validation.md` is missing, so the "
          "analyser is unvalidated and the structural labels are not yet ground truth.")
        A("")

    # ----------------------------------------------------------- minimal pairs
    A("## 5. Minimal pairs")
    A("")
    A("Source: `out/05_mine.json`, `out/05_pairs.json`, `data/minimal_pairs.csv`.")
    A("")
    if pairs and pairs.get("n_pairs"):
        A(f"{pairs['n_pairs']} usable pairs across {pairs['n_projects']} projects. Every "
          f"scorer was trained with all pair projects held out "
          f"({pairs['n_train_rows']} training rows).")
        A("")
        A("The prediction is **signed**: fixes for async flakiness usually *add* `await`, "
          "`join()` or a latch, so the post-fix version often carries *more* cue tokens. "
          "A model reading cue vocabulary therefore scores **below** 0.5; a model reading "
          "structure scores above it. The contrast between the scorers is the result.")
        A("")
        A("| scorer | PairAcc | 95% Wilson | binomial p | mean margin | cue-neutral PairAcc |")
        A("|---|---|---|---|---|---|")
        for name, e in pairs["scorers"].items():
            o = e["overall"]
            cn = e["by_stratum"].get("cue_neutral") or {}
            A(f"| `{name}` | {_f(o['pair_acc'])} | "
              f"[{_f(o['wilson_95'][0], 3)}, {_f(o['wilson_95'][1], 3)}] | "
              f"{_f(o['binom_p_two_sided'])} | {o['mean_margin']:+.4f} | "
              f"{_f(cn.get('pair_acc'))} (n={cn.get('n', 0)}) |")
        A("")
        A("Strata: " + ", ".join(f"{k} {v}" for k, v in pairs["strata_sizes"].items()) + ".")
        A("")
        sets = pairs.get("pair_sets") or {}
        if len(sets) > 1:
            A("Two pair sets were scored, because pair count and scorer strength trade "
              "against each other and neither choice dominates. Holding out a pair's project "
              "is mandatory, so more pairs means fewer training projects.")
            A("")
            A("| pair set | pairs | held-out projects | training rows | training flaky | "
              "probe PairAcc | bow PairAcc |")
            A("|---|---|---|---|---|---|---|")
            for name, es in sets.items():
                pr = next((v for k, v in es["scorers"].items() if k.startswith("probe_")), None)
                bw = es["scorers"].get("bow")
                star = " *(primary)*" if name == pairs.get("primary_pair_set") else ""
                A(f"| `{name}`{star} | {es['n_pairs']} | {es['n_held_out_projects']} | "
                  f"{es['n_train_rows']} | {es['n_train_flaky']} | "
                  f"{_f(pr['overall']['pair_acc']) if pr else '—'} | "
                  f"{_f(bw['overall']['pair_acc']) if bw else '—'} |")
            A("")
            A(f"`{pairs['primary_pair_set']}` is primary: `x_pre` is a test FlakeBench labels "
              f"flaky, which is stronger provenance than \"a test method the fix commit "
              f"happened to touch\", and holding out only its projects leaves a scorer with "
              f"several times more positive training examples. S3 reads it.")
            A("")
    else:
        A("No usable pairs were mined; S3 is inconclusive. See `out/05_mine.json` for the "
          "commit-level failure counts.")
        A("")

    # ------------------------------------------------------------------ probe
    A("## 6. Representations and probes")
    A("")
    A(f"Source: `out/06_probe.json`. Linear probes only — no nullspace projection, no "
      f"attention analysis; those are Phase 2 and are absent from this codebase. "
      f"Cross-project regime throughout.")
    A("")
    for mk, pools in probe["models"].items():
        for pl, e in pools.items():
            ex = probe["extraction"].get(f"{mk}|code", {})
            A(f"### `{mk}` / {pl} pooling — {e['n_layers']} layers, d={e['hidden_size']}")
            A("")
            A(f"Truncation rate {_f(ex.get('truncation_rate'), 4)} at max_length "
              f"{ex.get('max_length')}; peak VRAM {_f(ex.get('peak_vram_gb'), 2)} GB.")
            A("")
            A("| target | max AP | at layer | selectivity there | last-layer AP |")
            A("|---|---|---|---|---|")
            for tname, t in e["targets"].items():
                mx = t["max"]
                sel = t.get("selectivity_by_layer")
                sv = sel[mx["layer"]]["mean"] if sel else None
                A(f"| `{tname}` | {_f(mx['ap_mean'])} ± {_f(mx['ap_std'], 3)} | "
                  f"{mx['layer']} of {mx['n_layers_searched']} | {_f(sv)} | "
                  f"{_f(t['ap_by_layer'][-1]['mean'])} |")
            A("")
            A(f"Maxima are quoted with the number of layers searched, as required: they are "
              f"maxima over a searched curve, not held-out estimates. The full per-layer "
              f"curves are in `out/06_probe.json`.")
            A("")
    A("`control` is a random-label task matched to the class prior and fixed across folds. "
      "Selectivity S = AP(real) − AP(control): a probe with high AP and near-zero "
      "selectivity has capacity, not information.")
    A("")

    # -------------------------------------------------------- stopping rule
    A("## 7. The stopping rule, criterion by criterion")
    A("")
    A(f"Probe under test: `{model_key}` / {pool} pooling, layer {layer} of "
      f"{entry['n_layers']}, chosen by argmax of `flaky_code` cross-project AP on the main "
      f"dataset.")
    A("")
    A("### S1 — cue-removed probe vs the strong word baseline")
    A("")
    A("*Operationalisation.* \"Cue-removed probe\" is read as the probe evaluated on "
      "cue-removed input — trained on `code`, scored on `code_renamed` — against a word "
      "baseline that had full access to the cues. That is the Phase 1 question in `00`. "
      "Two other readings are reported below so the verdict can be checked under each.")
    A("")
    A("| framing | probe AP | baseline AP | mean diff | Wilcoxon p | verdict |")
    A("|---|---|---|---|---|---|")
    for name, w in s1["framings"].items():
        A(f"| {w['framing']} | {_f(w['probe_ap_mean'])} | {_f(w['baseline_ap_mean'])} | "
          f"{w['mean_diff']:+.4f} | {_f(w.get('p'))} | "
          f"{VERDICT_WORD[w['passes']]} |")
    A("")
    prim = s1["framings"]["primary_cue_removed"]
    A(f"Fold-level differences (probe − baseline), primary framing: "
      f"{_folds(prim['diff'])}; {prim['n_positive']} of {prim['n']} folds favour the probe. "
      f"With 5 folds the smallest attainable one-sided p is "
      f"{_f(prim['min_attainable_p'], 3)}, so a pass requires every fold to favour the "
      f"probe. Effect size: Cliff's δ {_f(prim['cliffs_delta'], 3)}, "
      f"Cohen's d_z {_f(prim.get('cohens_dz'), 3)}.")
    A("")
    if prim.get("passes"):
        A("A pass here says the probe carries signal a word baseline does not. It does **not** "
          "say that signal is structural: both encoders were pretrained on public GitHub "
          "including these repositories, so memorised project identity is an unexcluded "
          "alternative. Section 9 states this; S2 and S3 are what discriminate the two, "
          "which is why the rule requires all three.")
        A("")
    A("### S2 — transfer drop, probe vs word baseline")
    A("")
    A(f"Δ_probe = **{s2['delta_probe_mean']:+.4f}** (folds: {_folds(s2['delta_probe_folds'])})")
    A("")
    A(f"Δ_bow = **{s2['delta_bow_mean']:+.4f}** (folds: {_folds(s2['delta_bow_folds'])})")
    A("")
    A(f"The probe's drop is smaller in {s2['n_folds_probe_smaller']} of "
      f"{len(s2['delta_bow_folds'])} folds; paired Wilcoxon (bow − probe) p = "
      f"{_f(s2['paired_test_bow_minus_probe'].get('p'))}. Verdict "
      f"{VERDICT_WORD[s2['passes']]}.")
    A("")
    A("### S3 — minimal pairs")
    A("")
    if s3.get("status") == "inconclusive":
        A(f"{VERDICT_WORD[None]} — {s3.get('power_note', s3.get('reason', ''))}")
    else:
        A(f"PairAcc **{_f(s3['pair_acc'])}** "
          f"(95% Wilson [{_f(s3['wilson_95'][0], 3)}, {_f(s3['wilson_95'][1], 3)}], "
          f"binomial p {_f(s3['binom_p_two_sided'])}, mean margin "
          f"{s3['mean_margin']:+.4f}) over {s3['n_pairs']} pairs; `bow` scores "
          f"{_f(s3['bow_pair_acc'])}. Verdict {VERDICT_WORD[s3['passes']]}.")
        if s3.get("cue_neutral"):
            cn = s3["cue_neutral"]
            A("")
            A(f"On the cue-neutral subset — the cleanest test, since neither side gains or "
              f"loses cue tokens — the probe scores {_f(cn['pair_acc'])} over {cn['n']} pairs.")
    A("")

    # ------------------------------------------------------- interpretation
    A("## 8. What this means")
    A("")
    sv = verdict["split_verdict"]
    gap = base["methods"]["bow"]["full"]["gap"]
    abl = (base["methods"]["bow"]["full"]["cross"]["ap"]["mean"]
           - base["methods"]["bow_ablated"]["full"]["cross"]["ap"]["mean"])
    bow_delta = transfer["methods"]["bow"]["delta"]["mean"]
    s1p, s2p, s3p = s1.get("passes"), s2.get("passes"), s3.get("passes")

    if overall == "proceed_to_phase_2":
        A("All three criteria hold. Phase 2 — nullspace projection, attention analysis, and "
          "the inter-procedural property that needs repository checkout — is warranted.")
        A("")
    elif s1p and s2p and s3p is False:
        # The informative failure: invariant to surface, but blind to behaviour.
        A("**The probe is invariant to surface and blind to behaviour.** That is the finding, "
          "and it is a more specific result than either a clean pass or a flat negative.")
        A("")
        A(f"S1 and S2 both pass, and not narrowly. The probe scores "
          f"{_f(prim['probe_ap_mean'])} on cue-removed input against a word baseline's "
          f"{_f(prim['baseline_ap_mean'])} — every fold favours it — and its transfer drop "
          f"under renaming is {s2['delta_probe_mean']:+.4f} against `bow`'s "
          f"{s2['delta_bow_mean']:+.4f}. Read on their own, those two say the probe has found "
          f"something a bag of tokens has not, and that whatever it found does not live in the "
          f"cue vocabulary.")
        A("")
        sig = [n for n, e in pairs["scorers"].items()
               if e["overall"]["pair_acc"] < 0.5 and e["overall"]["binom_p_two_sided"] < 0.05]
        A(f"S3 says otherwise. On pairs where the behaviour changed and the surface barely "
          f"did, **every** scorer lands below 0.5 — none ranks the flaky version above the "
          f"fixed one. For the probe under test the interval still spans 0.5, so the honest "
          f"reading there is *no evidence of the predicted direction* rather than proof of "
          f"the opposite"
          + (f"; for {', '.join('`' + n + '`' for n in sig)} the reversal is itself "
             f"significant." if sig else "."))
        A("")
        A("| scorer | PairAcc | 95% Wilson | binomial p | direction |")
        A("|---|---|---|---|---|")
        for name, e in pairs["scorers"].items():
            o = e["overall"]
            if o["pair_acc"] >= 0.5:
                direction = "ranks the flaky version higher"
            elif o["binom_p_two_sided"] < 0.05:
                direction = "**significantly** below 0.5 — ranks the fixed version higher"
            else:
                direction = "below 0.5, interval spans it"
            A(f"| `{name}` | {_f(o['pair_acc'])} | [{_f(o['wilson_95'][0], 3)}, "
              f"{_f(o['wilson_95'][1], 3)}] | {_f(o['binom_p_two_sided'])} | {direction} |")
        A("")
        cn = s3.get("cue_neutral") or {}
        bcn = s3.get("bow_cue_neutral") or {}
        if cn.get("n"):
            A(f"The obvious explanation is the one the plan predicted: fixes *add* cue tokens "
              f"(`await`, `join()`, a latch), so a cue-reading model sees the fixed version as "
              f"more flaky. That explanation does not survive the cue-neutral subset — pairs "
              f"where neither side gains or loses a cue token. There the probe scores "
              f"{_f(cn['pair_acc'])} over {cn['n']} pairs (`bow`: {_f(bcn.get('pair_acc'))}). "
              f"Removing the cue asymmetry does not restore the direction, so cue-riding is "
              f"not the whole story.")
            A("")
        A("What is left is a probe keying on something **stable under renaming and unmoved by "
          "a behavioural fix** — which is what test "
          "style, project idiom, domain vocabulary the cue list never covered, and repository "
          "identity all look like. Two-sided invariance is what separates those from structural "
          "understanding, and it is exactly why the plan refused to define \"structural\" as "
          "residue after cue removal. A study that ran only S1 and S2 would have reported a "
          "positive result here.")
        A("")
        A("The corroboration points the same way. The three structural properties, labelled "
          f"independently of the flakiness label, predict it at AP "
          f"{_f(sv['structural_only_classifier_ap'])} against a prior of "
          f"{_f(sv['class_prior'])} — essentially nothing. Whatever the probe has learned, it "
          f"is not these properties, and these properties are not what makes this dataset's "
          f"tests flaky.")
        A("")
        A("What follows for practice:")
        A("")
        A(f"1. **Group by project, always.** `bow` scores {_f(gap['within_mean'])} "
          f"within-project and {_f(gap['cross_mean'])} cross-project — a gap of "
          f"{gap['mean']:+.4f}. A number reported without project grouping is measuring "
          f"interpolation.")
        A(f"2. **Ablate the cues.** Removing cue tokens from the feature space costs `bow` "
          f"{_f(abl)} AP and rewriting them in the source costs {_f(bow_delta)} more. Both "
          f"interventions are cheap; neither is standard.")
        A("3. **Report a behavioural test.** Surface invariance is not evidence of structural "
          "understanding, and this run is a worked example of the two coming apart. Minimal "
          "pairs from fix commits are the cheapest version of that test.")
        A("")
    elif s1p is False:
        A("S1 fails, so Phase 1 stops here. This negative result is a deliverable, not a "
          "fallback.")
        A("")
        A("The evidence, in order:")
        A("")
        A(f"1. **The generalisation problem is large.** `bow` scores {_f(gap['within_mean'])} "
          f"within-project and {_f(gap['cross_mean'])} cross-project — a gap of "
          f"{gap['mean']:+.4f}. Reported flaky-test classification numbers that do not group "
          f"by project are measuring interpolation.")
        A(f"2. **Cross-project performance is substantially lexical.** Removing cue tokens "
          f"from the feature space costs `bow` {_f(abl)} AP, and rewriting the cues in the "
          f"source costs it {_f(bow_delta)} more.")
        if pairs and pairs.get("n_pairs"):
            bowacc = pairs["scorers"].get("bow", {}).get("overall", {}).get("pair_acc")
            A(f"3. **The minimal pairs show the direction directly.** `bow` scores "
              f"{_f(bowacc)} on pairs where the post-fix version usually contains *more* cue "
              f"tokens" + (" — below 0.5, which is cue-riding shown rather than inferred."
                           if bowacc is not None and bowacc < 0.5 else "."))
        A("4. **Cue-ablated, project-grouped baselines should become standard reporting** for "
          "flaky test classification. Neither is expensive; without both, a reported score "
          "cannot be read as evidence about generalisation.")
        A("")
    else:
        A("The rule does not hold, so Phase 1 stops here. Section 7 gives the verdict for "
          "each criterion with its test statistic; the criterion that failed, and the one "
          "that could not be evaluated, are named there.")
        A("")
        A(f"For the record: the within- vs cross-project gap for `bow` is {gap['mean']:+.4f} "
          f"({_f(gap['within_mean'])} → {_f(gap['cross_mean'])}), cue ablation costs "
          f"{_f(abl)} AP, and counterfactual renaming costs a further {_f(bow_delta)}. "
          f"Cue-ablated, project-grouped baselines should become standard reporting for "
          f"flaky test classification regardless of how the rest of the rule lands.")
        A("")

    encodes = [p for p, v in sv["probe_encodes_properties_ap"].items()
               if v > sv["class_prior"] * 2]
    if s1.get("passes") is False and encodes:
        prop_ap = sv["probe_encodes_properties_ap"]
        listed = ", ".join(f"`{p}` AP {_f(prop_ap[p])}" for p in encodes)
        A(f"**Note the split verdict.** The probe fails S1 while still encoding "
          f"{listed} — above twice the class prior. The model represents the structure; the "
          f"structure does not predict this dataset's labels. That is a different and more "
          f"interesting finding than a flat negative, and the structural-only classifier "
          f"agrees: {_f(sv['structural_only_classifier_ap'])} AP against a prior of "
          f"{_f(sv['class_prior'])}.")
        A("")

    # -------------------------------------------------------- limitations
    A("## 9. Limitations")
    A("")
    A("- **The inter-procedural property is deferred.** A shared field written by one test "
      "and read by another needs the class body and sibling tests; it cannot be computed "
      "from FlakeBench's isolated method bodies and moves to Phase 2 with repository "
      "checkout.")
    if valid:
        def _p(kv):
            v = kv[1]["precision"]
            return (v if v == v else 2.0, -kv[1]["precision_wilson_95"][0])
        worst = min(valid["properties"].items(), key=_p)
        A(f"- **Static analyser precision is bounded by a {valid['n_audited']}-method audit** "
          f"performed by {valid['auditor']}, not by an independent human expert and with no "
          f"second opinion. Definitional precision is "
          + ", ".join(f"`{k}` {_f(v['precision'], 3)}" for k, v in valid["properties"].items())
          + f"; the loosest interval is `{worst[0]}` at 95% Wilson "
            f"[{_f(worst[1]['precision_wilson_95'][0], 2)}, "
            f"{_f(worst[1]['precision_wilson_95'][1], 2)}], because 50 methods bound these "
            f"estimates only loosely. Aliasing, field access and lambda capture are "
            f"approximated.")
        sem = valid.get("semantic") or {}
        if sem:
            ws = min(sem.items(), key=lambda kv: kv[1]["precision"])
            A(f"- **The properties as defined are looser than the properties as meant.** "
              f"Scored against what the code actually does rather than against the plan's "
              f"vocabulary, precision falls to "
              + ", ".join(f"`{k}` {_f(v['precision'], 3)}" for k, v in sem.items())
              + f". `{ws[0]}` is the worst. Every structural result in section 4, and the "
                f"per-property probe targets in section 6, inherit that looseness.")
        rec = valid["properties"].get("P_UNORD", {}).get("recall")
        if rec is not None and rec == rec and rec < 0.8:
            A(f"- **`P_UNORD` recall is {_f(rec, 3)}.** The analyser fires only when a value "
              f"*produced by iterating* an unordered collection reaches an assertion; a "
              f"collection passed into an opaque call is not counted, because doing so was "
              f"the source of every false positive in the audit. The cost is that genuine "
              f"cases which launder the collection through a helper are missed.")
        if valid.get("provenance", {}).get("development_pass"):
            A(f"- **The audit drove two rounds of analyser fixes.** {valid['provenance']['development_pass']}")
    else:
        A("- **The static analyser is unvalidated** — the hand audit has not been run, so the "
          "structural labels are not ground truth.")
    if pairs and pairs.get("n_pairs"):
        A(f"- **Minimal-pair count and mining filters.** {pairs['n_pairs']} pairs survived; "
          f"pairs whose diff exceeds 40% of tokens were excluded as no longer minimal, and "
          f"the excluded set is persisted with reasons in "
          f"`data/minimal_pairs_excluded.csv`. Pairs come from commits in "
          f"`dataset/filtered_tests_with_owner_sha.csv`, which is project-level rather than "
          f"test-level, so the mapping from commit to test method is recovered by name "
          f"matching and is not exhaustive.")
    else:
        A("- **No minimal pairs were usable**, so the converse test contributes nothing here.")
    A("- **Pretraining contamination is not controlled for.** Both models were pretrained "
      "on large public GitHub corpora, which include the projects this dataset is drawn "
      "from — and, for the minimal pairs, plausibly the fix commits themselves. A probe "
      "that beats a word baseline may be reading memorised project identity rather than "
      "program structure. Nothing in Phase 1 separates the two; the project-grouped split "
      "prevents a *classifier* from seeing a test project's training rows, but it cannot "
      "prevent the *encoder* from having seen the repository. This is the strongest "
      "alternative explanation for a positive S1 and it is not ruled out here.")
    A(f"- **Two-model scope.** `microsoft/codebert-base` and `Qwen/Qwen2.5-Coder-1.5B`, fp16 "
      f"on a single 8GB Turing card. No conclusion here generalises to larger models, and "
      f"the two see different amounts of code: CodeBERT caps at 512 tokens against Qwen's "
      f"1024.")
    A("- **Five folds** give the paired tests very little power; every fold-level value is "
      "printed above so the reader can judge the spread directly.")
    A("- Probing is linear and minimal by design. Nullspace projection and attention "
      "analysis are explicitly out of scope for Phase 1.")
    A("")

    A("## 10. Artefacts")
    A("")
    for name, what in [
        ("data/prepped.csv", "normalised corpus, one row per test"),
        ("data/cue_vocab.json", "cue vocabulary, tags separately ablatable"),
        ("data/rename_map.json", "the renaming bijection, invertible and auditable"),
        ("data/structural.csv", "structural property labels"),
        ("data/minimal_pairs.csv", "mined pairs with diffs and cue deltas"),
        ("data/minimal_pairs_excluded.csv", "what did not qualify, with reasons"),
        ("out/01_prep.json", "counts, assertions, the whitespace audit"),
        ("out/02_baselines.json", "per method/regime/subset, fold vectors, STRONG_WORD_BASELINE"),
        ("out/03_transfer.json", "transfer drop per method"),
        ("out/04_structural.json", "prevalence, cross-tabs, parse rates"),
        ("out/04_validation.md", "the hand audit"),
        ("out/05_pairs.json", "PairAcc per scorer, overall and per stratum"),
        ("out/06_probe.json", "full per-layer curves, selectivity, transfer"),
        ("out/07_decision.json", "the stopping rule evaluated, per criterion"),
        ("out/figures/", "layer curve, within-vs-cross, transfer drop, minimal pairs"),
    ]:
        A(f"- `{name}` — {what}")
    A("")
    return "\n".join(L)
